#!/usr/bin/env node
/**
 * Production bootstrap helper: create or verify the initial administrator
 * account, then print a JSON summary for scripts/setup.sh to consume.
 *
 * Reads from the environment (setup.sh loads these from .env):
 *   ADMIN_USERNAME      — login username (required)
 *   ADMIN_EMAIL         — login email (required)
 *   ADMIN_DISPLAY_NAME  — display name (required)
 *   ADMIN_PASSWORD      — initial random password generated by setup.sh (required)
 *
 * It talks to the local auth store directly (no HTTP), so it is NOT gated by
 * PUBLIC_REGISTRATION_ENABLED and it auto-verifies the email so the account
 * can log in even when REGISTRATION_EMAIL_VERIFICATION_REQUIRED is on.
 *
 * stdout is one JSON line:
 *   {"action":"created",...,"token":...}            → account created as admin
 *   {"action":"exists-logged-in",...,"token":...}   → admin already present, login ok
 *   {"action":"exists-no-password",...}             → admin present but password mismatch
 *   {"action":"admin-exists",...}                   → another admin already exists
 *   {"action":"error","code":...,"message":...}
 */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createAuthStoreFromEnv, loadDotEnvIfPresent } from "@skill-platform/storage";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
loadDotEnvIfPresent(path.join(repoRoot, ".env"));

function report(payload) {
  console.log(JSON.stringify(payload));
}

const username = process.env.ADMIN_USERNAME?.trim();
const email = process.env.ADMIN_EMAIL?.trim();
const displayName = process.env.ADMIN_DISPLAY_NAME?.trim();
const password = process.env.ADMIN_PASSWORD ?? "";

if (!username || !email || !displayName || !password) {
  report({
    action: "error",
    code: "missing-input",
    message: "ADMIN_USERNAME / ADMIN_EMAIL / ADMIN_DISPLAY_NAME / ADMIN_PASSWORD must all be set.",
  });
  process.exit(0);
}

let authStore;
try {
  authStore = createAuthStoreFromEnv();
} catch (error) {
  report({ action: "error", code: "store-init", message: String(error instanceof Error ? error.message : error) });
  process.exit(0);
}

async function main() {
  try {
    const users = await authStore.listUsers();
    const admins = users.filter((user) => user.role === "admin");

    if (admins.length > 0) {
      const matched = admins.find((user) => user.username.toLowerCase() === username.toLowerCase());
      if (!matched) {
        const names = admins.map((user) => user.username).join(", ");
        report({
          action: "admin-exists",
          username,
          email,
          message: `An administrator already exists (${names}). Point ADMIN_* at that account, or remove the ADMIN_* config to skip initialization.`,
        });
        return;
      }
      // The configured admin already exists — try to log in with the generated
      // password to decide whether the official Skill can be published.
      try {
        const session = await authStore.login(username, password);
        report({
          action: "exists-logged-in",
          username: session.user.username,
          email: session.user.email ?? email,
          token: session.token,
        });
      } catch {
        report({
          action: "exists-no-password",
          username,
          email,
          message: "The administrator already exists and the provided password cannot log in. Skill initialization is skipped; publish the official Skill manually if needed.",
        });
      }
      return;
    }

    // No admin yet → the registry is fresh. Registering the first user grants
    // the admin role automatically. Auto-verify the email so login works even
    // when verification is required in production.
    const user = await authStore.register(username, password, email, { autoVerifyEmail: true });
    const session = await authStore.login(username, password);
    if (displayName) {
      await authStore.updateProfile(session.token, { displayName });
    }
    report({
      action: "created",
      username: user.username,
      email: user.email ?? email,
      displayName,
      password,
      token: session.token,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    report({
      action: "error",
      code: "bootstrap-failed",
      message: `Admin bootstrap failed: ${message}`,
    });
  }
}

await main();
